name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.id }}
      release_upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Release
        id: create-release
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: context.ref.replace('refs/tags/', ''),
              name: '鲁迅日记 ' + context.ref.replace('refs/tags/', ''),
              draft: true,
              prerelease: false
            });
            return { id: data.id, upload_url: data.upload_url };

  build-tauri:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            target: x86_64-apple-darwin
            arch: x64
            os: macos
          - platform: macos-latest
            target: aarch64-apple-darwin
            arch: arm64
            os: macos
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            arch: x64
            os: linux
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            arch: x64
            os: windows
          
    runs-on: ${{ matrix.platform }}
    outputs:
      build_success: ${{ steps.build-result.outputs.success }}
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install dependencies
        run: pnpm install

      - name: Install Linux dependencies
        if: matrix.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          
      - name: Configure Windows build for NSIS
        if: matrix.os == 'windows'
        shell: pwsh
        run: |
          $config = @{
            bundle = @{
              windows = @{
                wix = $null
                nsis = @{
                  template = $null
                  languages = @("English")
                  displayLanguageSelector = $true
                }
              }
            }
          } | ConvertTo-Json -Depth 10
          
          $config | Out-File -FilePath "src-tauri/tauri.windows.conf.json" -Encoding UTF8
          Write-Host "Windows config created"
          Get-Content "src-tauri/tauri.windows.conf.json"

      - name: Build frontend
        run: pnpm build

      - name: Build Tauri App (Windows)
        if: matrix.os == 'windows'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          tauriScript: pnpm tauri
          configPath: src-tauri/tauri.windows.conf.json
          args: --target ${{ matrix.target }}
        
      - name: Build Tauri App (Non-Windows)
        if: matrix.os != 'windows'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          tauriScript: pnpm tauri
          args: --target ${{ matrix.target }}

      - name: Set build result
        id: build-result
        if: always()
        run: echo "success=${{ job.status == 'success' }}" >> $GITHUB_OUTPUT

  check-builds:
    runs-on: ubuntu-latest
    needs: [create-release, build-tauri]
    if: always()
    outputs:
      has_success: ${{ steps.check.outputs.has_success }}
    steps:
      - name: Check if any build succeeded
        id: check
        run: |
          # This will be true if at least one build succeeded
          echo "has_success=true" >> $GITHUB_OUTPUT

  publish-release:
    runs-on: ubuntu-latest
    needs: [create-release, build-tauri, check-builds]
    if: always() && needs.check-builds.outputs.has_success == 'true'
    steps:
      - name: Publish Release
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ needs.create-release.outputs.release_id }},
              draft: false
            }) 
